name: Build

on: [push, pull_request]

jobs:
  Build:
    runs-on: macos-latest
    steps:
    - name: Print environment
      run: |
        env
    - uses: actions/checkout@v2
    - name: Configure (CMake)
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=prefix
    - name: Build (CMake)
      run: |
        cmake --build build --config Release
    - name: Install (CMake)
      run: |
        cmake --install build --config Release
        ( cd prefix; find . ) | LC_ALL=C sort -u
    - name: Package (CPack)
      run: |
        cat -n build/cmake_install.cmake
        cmake --build build --config Release --target package
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        path: |
          build/*.dmg
        if-no-files-found: ignore
